DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views
from django.contrib.auth.views import LoginView, LogoutView

import app.forms
import app.views


from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),

    url(r'^links$', app.views.links, name='links'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^pool$', app.views.pool, name='pool'),
    url(r'^registration$', app.views.registration, name='registration'),
    
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings. MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ('text',)
        labels = {'text': "Комментарий"}

class BlogForm (forms.ModelForm):
    class Meta:
        model = Blog 
        fields = ('title', 'description', 'content', 'image',)
        labels = {'title': "Заголовок", 'description': "Краткое содержание", 'content': "Полное содержание", 'image': "Картинка",}

class Support(forms.Form):
        name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
        city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
        gender = forms.ChoiceField(label='Ваш пол',
                                  choices=[('1','Мужской'),('2','Женский')],
                                  widget=forms.RadioSelect, initial=1)
        abilities = forms.ChoiceField(label='Вы знаете английский', 
                                     choices=(('1','Не знаю'),
                                     ('2','Только основы'),
                                     ('3','Могу читать на английском'),
                                     ('4','Могу говорить на английском')), initial=1)
        email = forms.BooleanField(label='Получать нвости на e-mail', required=False)
        email = forms.EmailField(label='Ваш e-mail', min_length=7)
        message = forms.CharField(label='О себе', widget=forms.Textarea(attrs={'rows':12, 'cols':20}))

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Наша школа занимается обучением английского языка в школьных условиях.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{ title }}.</h2><br />

{% for post in posts %}
<hr/>
<div class="">
<h2> {{post.title}} </h2>
<h4> {{post.posted}} </h4>
<p> {{post.description}} </p>
<p> <a href="{% url 'blogpost' parametr=post.id %}">Читать далее </a></p>
</div>
{% endfor %}

{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}
<p><a href="{% url 'blog' %}">Назад</a></p>
<h2>{{ post_l.title }}.</h2>
{%if post_l.image and post_l.image.url != '/media/ru-eng.png' %}
    <img src="{{post_l.image.url}}" alt="Картинка" width="300" height="200"/>
{% endif %}

{% autoescape off%}
<p> {{post_l.content|linebreaksbr}} </p>
{% endautoescape %}

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="POST">{% csrf_token %}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-default" > Отправить комментарий </button>
    </div>
    </form>
{% else %}
    <h3> Для добавления своего комментария, пожалуйста, авторизуйтесь</h3>
{% endif %}
<div>{{number}}</div>

{% for comment in comments %}
<hr/>
<h7> {{comment.date}} </h7>
<h5> {{comment.author}} </h5>
<p> {{comment.text|linebreaksbr}} </p>
{% endfor %}


{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    NewHorizon<br />
    ENG, INC 65497-474<br />
    <abbr title="Phone">P: +79118830274</abbr>
    <p><a href="https://vk.com/id445134720">Старший преподаватель</a></p>
    425.555.0100
</address>

<address>
    <strong>Поддержка:</strong>   <a href="mailto:newhorizon@mail.ru">Создатель newhorizon@mail.ru Срогинис Роман</a><br />
</address>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="jumbotron">
    <h1>NewHorizon</h1>
    <p class="lead">Школа для обучения универсальному языку.</p>
    <p><a href="https://learnenglish.britishcouncil.org/online-courses" class="btn btn-primary btn-large"> Узнать больше &raquo;</a></p>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active">

            <img src="{% static 'app/content/NewHorizon.png'%} " alt="Первый слайд" class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Наша школа

                    <a class="btn btn-default" href="https://vk.com/id445134720">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src="{% static 'app/content/Russian_English_flag.png'%}" alt="Второй слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Английский для русскогоговорящих

                    <a class="btn btn-default" href="https://englishfull.ru/kursy/metod-pimslera.html">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

        <div class="item">

            <img src=" {% static 'app/content/eng.png'%} " alt="Третий слайд"  class="img-responsive" />

            <div class="carousel-caption" role="option">

                <p>

                    Подробнее об английском языке с азов

                    <a class="btn btn-default" href="https://lim-english.com/posts/anglijskij-dlya-nachinayushchikh-s-nulya/">

                        Читать далее

                    </a>

                </p>

            </div>

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

    </a>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>О нас</h2>
        <p>
            Наша школа собрала англоговорящих специалистов из разных уголков России и даже за ее пределами.
        </p>
        <p><a class="btn btn-default" href="https://vk.com/id445134720">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Наши услуги</h2>
        <p>
        В сферу наших услуг входит детальное обучение английскому языку и способности свободно общаться на нем.</p>
        <p><a class="btn btn-default" href="{% url 'links' %}">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Наши разработчики</h2>
        <p> Срогинис Роман
        Владислав Селецкий
        Давиденко Наталья
        .</p>
        <p><a class="btn btn-default" href="https://vk.com/id445134720">Узнать больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - NewHorizon</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <a href="/" class="navbar-brand"> <img src="{% static 'app\content\hqdefault1.jpg' %}" width="100px" alt="eng" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {#<li><a href="{% url 'home' %}">Главная</a font-size></li>#}
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Ресурсы</a></li>
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>

                    {%if user.is_superuser%}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>

                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - NewHorizon school<p>
        </footer>
    </div>

  
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
</head>
<body>
    <content>
        {% load staticfiles %}
    </content>
    <h2>Информация об отдельных занятиях школы</h2>
    <div class="dlinks">
    <a class="btn-dlinks-default" href ="https://vk.com/id445134720" target="_blank"> <img src="{% static 'app/content/audio.jpg' %}" alt="Logo1"/></a>
    <a class="btn-dlinks-default" href ="https://vk.com/id445134720" target="_blank"> <img src="{% static 'app/content/writing.JPG' %}" alt="Logo2"/></a>
    <a class="btn-dlinks-default" href ="https://vk.com/id445134720" target="_blank"> <img src="{% static 'app/content/reading.jpg' %}" alt="Logo3"/></a>
    </div>
</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте для входа свой ранее созданный аккаунт или зарегистрируйтесь.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользвателя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Вход" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста введите правильный пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выход</a></li>
    </ul>
</form>
{% else %}

<ul class="nav navbar-nav navbar-right">
                    {% if not user.is_authenticated %}
                <li><a href="{% url 'registration' %}">Регистрация</a></li>
                <li><a href="{% url 'login' %}">Вход</a></li>
                {% endif %}
    {% if user.is_authenticated %}
    <li><a href="{% url 'login' %}">Вход</a></li>
    {% endif %}
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}


<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
<div>
    {{ blogform.as_p}}
    <button type="submit" class="save btn btn-default" > Сохранить статью </button>
</div>
</form>

{% endblock %}

app/templates/app/pool.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>

    <meta charset="utf-8" />
    <title></title>

</head>

<body class="style-anket">
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
    
<br><h2>Пожалуйста заполните информацию о себе для связи.</h2> 
<h2>Информация будет использована только для связи с Вами.</h2><br>
 <div>
    <form method="POST">
    {% csrf_token %}
        <label for="{{ form.name.id_for_label }}" >{{ form.name.label }}: </label>
         {{ form.name }}<br><br>
        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
         {{ form.city }}<br>
        <label for="{{ form.gender.id_for_label }}">{{ form.gender.label }}:</label>
         {{ form.gender }}
        <label for="{{ form.abilities.id_for_label }}">{{ form.abilities.label }}:</label><br>
         {{ form.abilities }}<br><br>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
         {{ form.email }}<br><br>
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label><br>
        {{ form.message }}<br><br>
        <input  type="submit" value="Отправить" id="b1">
    </form>
     <script>
            function mouse_in()
            {
                $('#b1').css('background', 'green');
                $('#b1').css('color', 'red');
                
         }
         function mouse_out()
            {
             $('#b1').css('background', 'white');
             $('#b1').css('color', 'black');
         
            }
        
          function focus_in()
            {
              $('#id_name').css('background', 'red');
   
         }
          function focus_out()
            {
              $('#id_name').css('background', 'white');

         }
          function focus_in1()
            {
              $('#id_city').css('background', 'lightgreen');

         }
          function focus_out1()
            {
              $('#id_city').css('background', 'white');

         }
          function focus_in3()
            {
              $('#id_email').css('background', 'green');

         }
          function focus_out3()
            {
              $('#id_email').css('background', 'white');
              setTimeOut(alert("Разработчик сайта Sroginis. R.V.)",1000)
         }
                   function focus_in4()
            {
                       $('#id_message').css('background', 'lightgreen');
         }
          function focus_out4()
            {
              $('#id_message').css('background', 'white');
     
         }
         $('#b1').mouseover(mouse_in);
         $('#b1').mouseout(mouse_out);
         $('#id_name').focus(focus_in);
         $('#id_name').blur(focus_out);
         $('#id_city').focus(focus_in1);
         $('#id_city').blur(focus_out1);
         $('#id_email').focus(focus_in3);
         $('#id_email').blur(focus_out3);
         $('#id_message').focus(focus_in4);
         $('#id_message').blur(focus_out4);
     </script>
</div>
{% else %}
<br><h2>Спасибо за обращение. Ответ придёт на указанный  email.</h2>
<h3>Вы сообщили о себе следующее:</h3>
<ul>
    <li><span>Имя: </span> {{ data.name }}</li>
    <li><span>Город: </span> {{ data.city }}</li>
    <li><span>Пол: </span> {{ data.gender }}</li>
    <li><span>Знание английского: </span> {{ data.abilities }}</li>
    <li><span>Ваш e-mail:</span> {{ data.email }} </li>
    <li><span>Текст обращения:</span>{{ data.message }}</li>
</ul>
{% endif %}
{% endblock %}
</body>
</html>

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="POST" > {% csrf_token %}

<div>

{{ regform.as_p}}

<button type="submit" class="save btn btn-default" > Зарегистрировать </button>

</div>

</form>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}
{% block content %}

<div>
<h1>Видео-ролик 1</h1>
<VIDEO src="/media/New Horizon.mp4" controls="controls" width="400" height="300" poster="/media/english.jpg">
</div>
<hr/>
<div>
<h1>Видео-ролик 2</h1>
<VIDEO src="/media/Greeting.mp4" controls="controls" width="400" height="300" poster="/media/NewHorizon.png">
</div>


{% endblock %}